/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.util.*;

import javafx.scene.media.Media;  
import javafx.scene.media.MediaPlayer;
import javafx.embed.swing.JFXPanel;
/**
 *
 * @author avitu
 */
public class ThirdEyeMusicPlayer extends javax.swing.JFrame {

    DefaultListModel<String> songList = new DefaultListModel<>();
    ArrayList<String> list = new ArrayList<String>();
    int i = 0;
    private MediaPlayer mediaPlayer ;
    double volume = 0;
    /**
     * Creates new form ThirdEyeMusicPlayer
     */
    public ThirdEyeMusicPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        volumeSlider = new javax.swing.JSlider();
        playPauseBtn = new javax.swing.JButton();
        forwordBtn = new javax.swing.JButton();
        backwardBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        muteUnmuteBtn = new javax.swing.JButton();
        rewindBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        runningTime = new javax.swing.JLabel();
        totalTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playList = new javax.swing.JList<>();
        addSong = new javax.swing.JButton();
        deleteSong = new javax.swing.JButton();
        songName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3rdEye-Music-Player");
        setBackground(new java.awt.Color(51, 51, 51));
        setIconImage(Toolkit.getDefaultToolkit().getImage(ThirdEyeMusicPlayer.class.getResource("images/3rdEye.png")));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        volumeSlider.setBackground(new java.awt.Color(0, 0, 0));
        volumeSlider.setForeground(new java.awt.Color(0, 0, 102));
        volumeSlider.setValue(100);
        volumeSlider.setName("speakerSlider"); // NOI18N
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });

        playPauseBtn.setBackground(new java.awt.Color(0, 0, 0));
        playPauseBtn.setForeground(new java.awt.Color(255, 255, 255));
        playPauseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        playPauseBtn.setToolTipText("Play-Pause");
        playPauseBtn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        playPauseBtn.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        playPauseBtn.setName("playPauseBtn"); // NOI18N
        playPauseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playPauseBtnMouseClicked(evt);
            }
        });

        forwordBtn.setBackground(new java.awt.Color(0, 0, 0));
        forwordBtn.setForeground(new java.awt.Color(255, 255, 255));
        forwordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forward.png"))); // NOI18N
        forwordBtn.setName("nextBtn"); // NOI18N

        backwardBtn.setBackground(new java.awt.Color(0, 0, 0));
        backwardBtn.setForeground(new java.awt.Color(255, 255, 255));
        backwardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backword.png"))); // NOI18N
        backwardBtn.setName("previousBtn"); // NOI18N

        stopBtn.setBackground(new java.awt.Color(0, 0, 0));
        stopBtn.setForeground(new java.awt.Color(255, 255, 255));
        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.png"))); // NOI18N
        stopBtn.setName("stopBtn"); // NOI18N
        stopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopBtnMouseClicked(evt);
            }
        });

        muteUnmuteBtn.setBackground(new java.awt.Color(0, 0, 0));
        muteUnmuteBtn.setForeground(new java.awt.Color(255, 255, 255));
        muteUnmuteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Volume1.png"))); // NOI18N
        muteUnmuteBtn.setName("speakerBtn"); // NOI18N
        muteUnmuteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muteUnmuteBtnMouseClicked(evt);
            }
        });

        rewindBtn.setBackground(new java.awt.Color(0, 0, 0));
        rewindBtn.setForeground(new java.awt.Color(255, 255, 255));
        rewindBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rewindBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backwardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playPauseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forwordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muteUnmuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(playPauseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backwardBtn)
                        .addComponent(forwordBtn)
                        .addComponent(muteUnmuteBtn)
                        .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rewindBtn)
                    .addComponent(stopBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to 3rdEye-Music-Player");
        jLabel1.setName("welcomelbl"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        progressBar.setBackground(new java.awt.Color(0, 0, 0));
        progressBar.setForeground(new java.awt.Color(0, 0, 204));
        progressBar.setName("progressBar"); // NOI18N
        progressBar.setOpaque(true);

        runningTime.setBackground(new java.awt.Color(0, 0, 0));
        runningTime.setForeground(new java.awt.Color(255, 255, 255));
        runningTime.setText("00:00");

        totalTime.setBackground(new java.awt.Color(0, 0, 0));
        totalTime.setForeground(new java.awt.Color(255, 255, 255));
        totalTime.setText("00:00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(runningTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runningTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalTime, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        playList.setBackground(new java.awt.Color(0, 0, 0));
        playList.setForeground(new java.awt.Color(255, 255, 255));
        playList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        playList.setAlignmentX(0.0F);
        playList.setAlignmentY(0.0F);
        playList.setName("songList"); // NOI18N
        jScrollPane1.setViewportView(playList);

        addSong.setBackground(new java.awt.Color(0, 0, 0));
        addSong.setForeground(new java.awt.Color(255, 255, 255));
        addSong.setText("+");
        addSong.setName("addSong"); // NOI18N
        addSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSongMouseClicked(evt);
            }
        });

        deleteSong.setBackground(new java.awt.Color(0, 0, 0));
        deleteSong.setForeground(new java.awt.Color(255, 255, 255));
        deleteSong.setText("-");
        deleteSong.setName("deleteSong"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSong, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        songName.setBackground(new java.awt.Color(0, 0, 0));
        songName.setForeground(new java.awt.Color(255, 255, 255));
        songName.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(songName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(songName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 0));
        jMenuBar1.setName(""); // NOI18N

        file.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        buttonGroup1.add(open);
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        file.add(open);

        exit.setText("Exit");
        buttonGroup1.add(exit);
        file.add(exit);

        jMenuBar1.add(file);

        help.setText("Help");
        jMenuBar1.add(help);

        about.setText("About-us");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        boolean play = false;
    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        try{
            ImageIcon icon = new ImageIcon(getClass().getResource("images/3rdEye.png"));
            JOptionPane.showMessageDialog(this, "This is a music player build using Java \n by Avinash Kumar @3rdEye-Technosolution","About 3rdEye-Music-Player",1, icon);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage() , "Error" , 0);
            }
    }//GEN-LAST:event_aboutMouseClicked

    private void addSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSongMouseClicked
        // TODO add your handling code here:
        try{
            JFileChooser fc=new JFileChooser();   
            FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3");
            fc.setFileFilter(filter);
            int no = fc.showOpenDialog(this);
            if(no == JFileChooser.APPROVE_OPTION){
                File file = fc.getSelectedFile();            
                list.add(i, file.getPath());
                System.out.println(i+file.getPath());
               songList.add(i, file.getName());
                System.out.println(i +""+file.getName());
               i++;
               playList.setModel(songList);
               playList.setSelectedIndex(0);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_addSongMouseClicked

    private void playPauseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playPauseBtnMouseClicked
        // TODO add your handling code here:
         System.out.println(play);
        try{
            if(playList.isSelectionEmpty())
                JOptionPane.showMessageDialog(this, "Please Select Song", "Error", 0);
            else{
                if(mediaPlayer != null && play == true){
                    ImageIcon icon = new ImageIcon(getClass().getResource("images/play.png"));
                    playPauseBtn.setIcon(icon);
                    mediaPlayer.pause();
                    play = false;
                }
                else if(mediaPlayer != null && play == false){
                    ImageIcon icon = new ImageIcon(getClass().getResource("images/pause.png"));
                    playPauseBtn.setIcon(icon);
                    mediaPlayer.play();
                    play = true;
                 }
                else{
                    int index = playList.getSelectedIndex();
                    String path = list.get(index);
                    songName.setText(songList.getElementAt(index));
                    Media media = new Media(new File(path).toURI().toString());
                    this.mediaPlayer = new MediaPlayer(media);
                    ImageIcon icon = new ImageIcon(getClass().getResource("images/pause.png"));
                    playPauseBtn.setIcon(icon);
                    mediaPlayer.play();
                    play = true;
                   
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_playPauseBtnMouseClicked
    
    private void muteUnmuteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muteUnmuteBtnMouseClicked
        // TODO add your handling code here:
        if(mediaPlayer.getVolume() > 0){
            volume = mediaPlayer.getVolume();
            ImageIcon icon = new ImageIcon(getClass().getResource("images/mute1.png"));
            muteUnmuteBtn.setIcon(icon);
            mediaPlayer.setVolume(0);
        }
        else{
            ImageIcon icon = new ImageIcon(getClass().getResource("images/volume1.png"));
            muteUnmuteBtn.setIcon(icon);
            mediaPlayer.setVolume(volume);
        }
    }//GEN-LAST:event_muteUnmuteBtnMouseClicked

    private void stopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseClicked
        // TODO add your handling code here:
        if(mediaPlayer != null && play == true){
            ImageIcon icon = new ImageIcon(getClass().getResource("images/play.png"));
            playPauseBtn.setIcon(icon);
            mediaPlayer.stop();
            mediaPlayer = null;
            play = false;
        }
    }//GEN-LAST:event_stopBtnMouseClicked

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser fc=new JFileChooser();   
            FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3");
            fc.setFileFilter(filter);
            int no = fc.showOpenDialog(this);
            if(no == JFileChooser.APPROVE_OPTION){
                File file = fc.getSelectedFile();            
                list.add(i, file.getPath());
                System.out.println(i+file.getPath());
               songList.add(i, file.getName());
                System.out.println(i +""+file.getName());
               i++;
               playList.setModel(songList);
               playList.setSelectedIndex(0);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_openActionPerformed

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        // TODO add your handling code here:
        float vol = (float)volumeSlider.getValue()/100;
        mediaPlayer.setVolume(vol);
        if(volumeSlider.getValue()>0){
           ImageIcon icon = new ImageIcon(getClass().getResource("images/volume1.png"));
            muteUnmuteBtn.setIcon(icon); 
        }
        else{
            ImageIcon icon = new ImageIcon(getClass().getResource("images/mute1.png"));
            muteUnmuteBtn.setIcon(icon);
        }
    }//GEN-LAST:event_volumeSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdEyeMusicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdEyeMusicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdEyeMusicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdEyeMusicPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFXPanel();
                new ThirdEyeMusicPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton addSong;
    private javax.swing.JButton backwardBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteSong;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JButton forwordBtn;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton muteUnmuteBtn;
    private javax.swing.JMenuItem open;
    private javax.swing.JList<String> playList;
    private javax.swing.JButton playPauseBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton rewindBtn;
    private javax.swing.JLabel runningTime;
    private javax.swing.JLabel songName;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel totalTime;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
